# Generated by Django 2.0 on 2018-01-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20171228_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='original_content_type',
        ),
        migrations.RemoveField(
            model_name='placeimage',
            name='original_file_name',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
