# Generated by Django 2.0 on 2018-01-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20180101_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeimage',
            old_name='image',
            new_name='file',
        ),
    ]
