# Generated by Django 2.0 on 2018-01-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20180101_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeimage',
            old_name='file',
            new_name='image',
        ),
    ]
