# Generated by Django 2.0 on 2018-01-03 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20180102_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
